# Generated by Django 6.0.2 on 2026-02-25 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framed',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('paraula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('categories', models.ManyToManyField(related_name='games', to='udltimes.connectionscategory')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.connectionscategory')),
            ],
            options={
                'unique_together': {('category', 'word')},
            },
        ),
        migrations.CreateModel(
            name='FramedGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.framed')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'order'), name='unique_game_order_framedgamedata')],
            },
        ),
        migrations.CreateModel(
            name='StatsConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.connections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='StatsFramed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.framed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game_statsframed')],
            },
        ),
        migrations.CreateModel(
            name='StatsWordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.wordle')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
