# Generated by Django 6.0.2 on 2026-02-25 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paraula', models.CharField(max_length=100, unique=True)),
                ('paraula', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.connections')),
            ],
        ),
        migrations.CreateModel(
            name='FramedGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.framed')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatsFramed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.framed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.user')),
            ],
        ),
        migrations.CreateModel(
            name='StatsConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.connections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.user')),
            ],
        ),
        migrations.CreateModel(
            name='StatsWordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.user')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udltimes.wordle')),
            ],
        ),
    ]
