# Generated by Django 6.0.2 on 2026-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udltimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsconnections',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
