# Generated by Django 6.0.3 on 2026-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udltimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statswordle',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statswordle',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statswordle',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
