# Generated by Django 6.0.2 on 2026-04-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udltimes', '0003_merge_20260418_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsconnections',
            name='points',
        ),
    ]
