# Generated by Django 6.0.2 on 2026-04-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udltimes', '0004_remove_statsconnections_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsconnections',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
