# Generated by Django 6.0.2 on 2026-04-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udltimes', '0002_statsframed_points'),
        ('udltimes', '0005_statsconnections_points'),
    ]

    operations = [
    ]
